### ISSUE TITLE
Add screenshot in README.md 

### ISSUE THREAD

**Issue by Atli-A** [zphyrj/forest-cottage-theme#1]
It would show what the theme looks like you know.

**Comment by zphrs** [comment]
If you would like to make a pull request to add example images be my guest. You should just be able to add a relative link in the readme.md file with this formatting and upload example images to the images directory:
```markdown
![example of theme](images/example.png)
```

**Comment by zphrs** [comment]
Never mind, I added some example images along with a demo folder from night owl and updated the readme accordingly. https://github.com/zphyrj/forest-cottage-theme/commit/a2985f23de59589c8b2175f3cc7a921f3695a74b
